### ISSUE TITLE
App crashes when closing the 'settings' dialog box

### ISSUE THREAD

**Issue by not-magic** [Yeicor/sdf-viewer#371]
Repro: open the 'settings' menu and then press the 'x'. Expected behavior is to just close the setting box.

Crashes here:

```
thread 'main' panicked at src/app/cli/settings.rs:77:54:
called `Option::unwrap()` on a `None` value
```

This was synced to [7aa5976](https://github.com/Yeicor/sdf-viewer/commit/7aa5976b8eca9bdbb59247c762ce07ea7abfdd65) and built locally

**Comment by Yeicor** [comment]
Thanks for the report, it should be fixed now!
