### ISSUE TITLE
Gamma correction is off (Linux)

### ISSUE THREAD

**Issue by not-magic** [Yeicor/sdf-viewer#372]
The image is overly dark when I run it, and I need a gamma correction similar to the wasm32 code path.

But it also seems like shouldn't need to do manual gamma correction at all, as long as the frame buffer is in sRGB you should be able to just write your linear colors to it and it will be converted according to the monitor gamma curve correctly. (AFAIK... it's been a minute since I've last figured out a gamma pipeline)

Removing the gamma correction code from the .frag and making it enable sRGB with:

```
        unsafe {
            use eframe::glow::HasContext as _;
            context.enable(eframe::glow::FRAMEBUFFER_SRGB);
        }
```
... in  `FrameInput::new` makes it appear correct for me.

**Comment by Yeicor** [comment]
I've implemented this in v0.5.1. Sadly, the web build stopped working after some unknown third-party update (before v1.5.0) and I can no longer test whether the colors are the same for web and native builds.
