### ISSUE TITLE
rendering artifacts

### ISSUE THREAD

**Issue by GlennWSo** [Yeicor/sdf-viewer#381]
![20240913_12h53m14s_grim](https://github.com/user-attachments/assets/f3b3cad7-2e26-4c4b-b305-191305f58060)
![20240913_12h54m58s_grim](https://github.com/user-attachments/assets/2cbc4545-f79c-40aa-91fa-33256d475bb7)

When rendering varius types of sdf i see alot of black/white pixels in the 3d viewer.

What do you think is the likely culprit? 
And do you have any ideas of changes that I could try on either:
- app/rendering code?
- SDFSurface impl?

**Comment by Yeicor** [comment]
This is likely a precision issue on the shader code that runs on the GPU. I remember also experiencing it sometimes but never getting around to fixing it.

If it is an issue with the shader, you can try changing [this file](https://github.com/Yeicor/sdf-viewer/blob/master/src/app/scene/sdf/material.frag) and recompiling.

Unfortunately, I no longer have a use for this project, but I maintain it since there is still some interest in it. If you manage to mitigate or fix it, feel free to open a PR with the changes.

**Comment by GlennWSo** [comment]
Thanks for the hint, i look into to shader. Because i get the same artifacts even when rendering the 
SDFDemoSphere.

![20240913_13h27m35s_grim](https://github.com/user-attachments/assets/36d6194f-35b3-4f99-a962-097cea76589c)

I have never worked with shader/glsl files before, but what better time to start learning then now ;)
Anywas ill will try to mess with shader files, if I find anything usefull ill update this issue and perhaps open a pr

**Comment by GlennWSo** [comment]
one observation is that the problem occurs when the camera sufficiently zoomed out. 

above 6.5 seems to a threshold for me. Bellow this distance i dont notice any artifacts
> [src/app/scene/camera/mod.rs:71:76] new_distance = 6.732902

**Comment by GlennWSo** [comment]
![20240913_14h55m49s_grim](https://github.com/user-attachments/assets/c1286fb7-1cc2-4dab-a72c-113af76ae195)

i removed the black pixels but my changes hade some unwanted side effects :stuck_out_tongue_winking_eye:

**Comment by GlennWSo** [comment]
a small tweaak to the out of bounds condition seems to fix the issue. By only stopping when out bb with some **small margin** to black pixel artifacts seems to go away.


### material.frag
```
vec4[2] sdfRaycast(vec3 rayPos, vec3 rayDir, int maxSteps) {
		...

	    // Stop condition: out of bounds
        // limit was 0.0 use a small number here becouse it to avoid pixel artifacts
        // NOTE: the bounding boxes of SDF should perhaps have this same margin??
        if (sdfOutOfBoundsDist(rayPos) > 1e-4) { 
            hitPosAndSample[0] = vec4(rayPos, -2.0);
            break;
        }
```



Ill open a PR soon :tm: 

I haven not done rigorous testing, but first impression is that  I can now zoom out as much I like without any problems. :smile: 

![20240913_16h26m44s_grim](https://github.com/user-attachments/assets/c61eeffe-0903-40f6-8abe-ef8071445b88)

**Comment by Yeicor** [comment]
Nice work! I'll release v1.5.2 with this fix.

**Comment by GlennWSo** [comment]
Cool, Ill now add GPU expert to my CV :wink:
