### ISSUE TITLE
Online Demo is not working

### ISSUE THREAD

**Issue by Evil-Spirit** [Yeicor/sdf-viewer#393]
As I go to the [page](https://yeicor.github.io/sdf-viewer/?cliurl=https://yeicor.github.io/sdf-viewer-go/sdf-viewer-go-sdfx.wasm&envdark), some UI dispalyed in short moment, then starts to enlarge infinitely, and page stucks.
![sdf_bug](https://github.com/user-attachments/assets/6f3109db-68aa-4949-9687-53ed64095ad7)

**Comment by Yeicor** [comment]
Fixed in v1.5.3. The same link should now work. Thanks for reporting!

**Comment by Evil-Spirit** [comment]
Thanks, now works
