### ISSUE TITLE
birdhouse sample preview a little grainy

### ISSUE THREAD

**Issue by axaluss** [Yeicor/sdf-viewer#424]
would be nice to have some resolution and algorithm params for the viewer cli

[birdhouse.go.zip](https://github.com/user-attachments/files/17911729/birdhouse.go.zip)

![image](https://github.com/user-attachments/assets/d754966a-4f2d-4e43-9a60-6b0374b123b3)

**Comment by Yeicor** [comment]
I added a couple of parameters to control the resolution and the number of passes (for faster feedback at lower resolutions). They should be configurable via the CLI, query parameters, and GUI in the desktop and browser apps.

However, the rendering algorithm is not designed for small features and will quickly reach its limits if increasing the resolution. I recommend focusing the SDF bounds on the area you are working on, or working with bigger features while designing.
