### ISSUE TITLE
What would it take to create a vscode version for the plugin?

### ISSUE THREAD

**Issue by jotix16** [Yeicor/sdf-viewer#96]

**Comment by Yeicor** [comment]
Hi, thanks for your interest in the project.

I don't see a need to create a plugin: VS Code already allows you to open terminals and render an embedded webpage, and that's all you need to use this project completely inside VS Code.

Demo from [SDF Viewer Go](https://github.com/Yeicor/sdf-viewer-go):

![Screenshot_20221129_201659](https://user-images.githubusercontent.com/4929005/204624727-dcf264d3-3b4f-429a-8f77-93138e854ee3.png)
